name: CI/CD Pipeline for Yarn Monorepo with Lerna

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  Deploy:
    name: Deploying packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Run linter
        run: yarn lint

      - name: Building dist packages
        run: yarn lerna:build

      - name: Run tests
        run: yarn test

      - name: Authenticate to NPM
        run: echo "//registry.npmjs.com/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Bootstrap Lerna
        run: npx lerna bootstrap

      - name: Publish packages
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx lerna publish patch --yes
